"""empty message

Revision ID: 4359149df191
Revises: 
Create Date: 2019-05-21 23:37:36.484116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4359149df191'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('lastname', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('storename', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'storename')
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    # ### end Alembic commands ###
