"""empty message

Revision ID: 612f5c14d4c1
Revises: 
Create Date: 2019-05-24 02:01:35.826922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612f5c14d4c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('upgraded', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'upgraded')
    # ### end Alembic commands ###
