"""empty message

Revision ID: dbe29ea636ac
Revises: 
Create Date: 2019-05-19 21:59:08.413469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe29ea636ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_page', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('add_to_cart', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('go_to_checkout', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('personal_info', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('payment_info', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('payment_button', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tests')
    # ### end Alembic commands ###
